src/Entity/Game.php
<?php

namespace App\Entity;

use App\Repository\GameRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=GameRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Game
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Equipe::class, inversedBy="gamesEquipe1")
     */
    private $equipe1;

    /**
     * @ORM\ManyToOne(targetEntity=Equipe::class, inversedBy="gamesEquipe2")
     */
    private $equipe2;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dateGame;

    /**
     * @ORM\Column(type="integer")
     */
    private $ScoreEquipe1;

    /**
     * @ORM\Column(type="integer")
     */
    private $ScoreEquipe2;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $createAt;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $updatedAt;

    public function __construct()
    {
        $this->ScoreEquipe1 = 0;
        $this->ScoreEquipe2 = 0;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEquipe1(): Equipe
    {
        return $this->equipe1;
    }

    public function setEquipe1(?Equipe $equipe1): self
    {
        $this->equipe1 = $equipe1;

        return $this;
    }

    public function getEquipe2(): Equipe
    {
        return $this->equipe2;
    }

    public function setEquipe2(?Equipe $equipe2): self
    {
        $this->equipe2 = $equipe2;

        return $this;
    }

    public function getDateGame(): ?\DateTimeInterface
    {
        return $this->dateGame;
    }

    public function setDateGame(?\DateTimeInterface $dateGame): self
    {
        $this->dateGame = $dateGame;

        return $this;
    }

    public function getScoreEquipe1(): ?int
    {
        return $this->ScoreEquipe1;
    }

    public function setScoreEquipe1(int $ScoreEquipe1): self
    {
        $this->ScoreEquipe1 = $ScoreEquipe1;

        return $this;
    }

    public function getScoreEquipe2(): ?int
    {
        return $this->ScoreEquipe2;
    }

    public function setScoreEquipe2(int $ScoreEquipe2): self
    {
        $this->ScoreEquipe2 = $ScoreEquipe2;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeImmutable
    {
        return $this->createAt;
    }

    public function setCreateAt(\DateTimeImmutable $createAt): self
    {
        $this->createAt = $createAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
    * @ORM\PrePersist
    * @ORM\PreUpdate
    */
    public function updateTimesStamps(): void
    {
        if ($this->getCreateAt() === null) {
            $this->setCreateAt(new \DateTimeImmutable());
        }

        $this->setUpdatedAt(new \DateTimeImmutable());
    }
}

src/Controller/WorldController.php
<?php

namespace App\Controller;

use App\Entity\Game;
use App\Repository\GameRepository;
use Doctrine\ORM\EntityManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class WorldController extends AbstractController
{
    /**
     * @Route("/world", name="world_index")
     * @param GameRepository $gameRepository
     * @return Response
     */
    public function index(
        GameRepository $gameRepository
    ): Response {
        $games = $gameRepository->findBy([], ['dateGame' => 'ASC']);
        return $this->render('world/index.html.twig', [
            'games' => $games,
        ]);
    }
}

templates/world/index.html.twig
    {% extends 'base.html.twig' %}

{% set dateGame = '' %}

{% block title %}Hello WorldController!{% endblock %}

{% block body %}
<div class="container-fluid mt-5">

    <div class="row">
        <div class="col-8">
            <ul class="list-matchs-comp">
                {% for game in games %}
                    {% if game.dateGame | date('d/m/Y') != dateGame %}
                        {% set dateGame = game.dateGame | date('d/m/Y')%}
                        <h3 class="my-3 ms-4">{{ game.dateGame | date('D d F') }}</h3>
                    {% endif %}
                <li>
                    <div class="match-row finished">
                        {% if game.scoreEquipe1 != 0 or game.scoreEquipe2 != 0 %}
                            <div class="badge">Terminé</div>
                        {% else %}
                            <div class="badge">{{ game.dateGame | date('H:i') }}</div>
                        {% endif %}

                        <div class="versus-part">
                            <div class="team">
                                <div class="team-name">{{ game.equipe1.name }}</div>
                                <div class="team-logo">
                                    <img src="{{ vich_uploader_asset(game.equipe1, "imageFile") }}" alt="{{ game.equipe1.name }}" width="50" height="50">
                                </div>
                            </div>
                            <div class="score-versus">
                                <div class="score {% if game.scoreEquipe1 %} winning {% endif %}">{{ game.scoreEquipe1 }}</div>
                                <div class="score-vs">vs</div>
                                <div class="score {% if game.scoreEquipe2 %} winning {% endif %}">{{ game.scoreEquipe2 }}</div>
                            </div>
                            <div class="team">
                                <div class="team-logo">
                                    <img src="{{ vich_uploader_asset(game.equipe2, "imageFile") }}" alt="DWG KIA" width="50" height="50">
                                </div>
                                <div class="team-name">{{ game.equipe2.name }}</div>
                            </div>
                        </div>
                        <div class="tournament-part">
                            {%  set group = "Groupe " ~ game.equipe1.groupe %}
                            <div class="step" title="{{ group }}">{{ group }}</div>
                            <div class="logo-tn">
                                <img src="https://cdn.pandascore.co/images/league/image/297/220px-Worlds_2020.png" alt="Group A" width="40" height="100%">
                            </div>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}